name: Automatically sync to a fork repository
on:
  push:
    branches:
      - feature/auto-sync-with-github-action

jobs:
  fetch:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Fetch from Fork Repository
      run: |
        git remote add fork_repo https://daview-next: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@github.com/daview-next/daview-ui.git
        git fetch

    - name: log
      run: |
         git remote -v

    - name: Merge changes into develop
      run: |
        git switch fork_repo/feature/auto-sync-with-github-action --detach
        git merge origin/feature/auto-sync-with-github-action
        git push fork_repo feature/auto-sync-with-github-action
