name: Sync to Fork Repository

on:
  push:
    branches:
      - feature/auto-sync-with-github-action  # 원하는 브랜치명으로 변경

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Push to Fork Repository
        run: |
          git remote add fork_repo git@github.com:daview-next/daview-ui.git
          git fetch fork_repo