name: Sync Repository

on:
  push:
    branches:
      - feature/auto-sync-with-github-action  # 또는 동기화하려는 브랜치 이름

permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository A
      uses: actions/checkout@v2
      with:
        repository: meetup-fe-next/daview-ui  # 레포지토리 A의 경로
        ref: ${{ github.event.ref }}
    
    - name: Push to repository B
      uses: ad-m/github-push-action@master
      with:
        repository: daview-next/daview-ui  # 레포지토리 B의 경로
        github_token: ${{ secrets.FORK_GITHUB_TOKEN }}  # 레포지토리 B에 접근할 토큰




