name: Sync to Fork Repository

on:
  push:
    branches:
      - feature/auto-sync-with-github-action  # 원하는 브랜치명으로 변경

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Push to B Repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add fork_repo https://github.com/daview-next/daview-ui.git
          git push fork_repo HEAD:$GITHUB_REF
        env:
          GITHUB_TOKEN: ${{ secrets.FORK_GITHUB_TOKEN }}