name: Automatically sync to a fork repository
on:
  push:
    branches:
      - feature/auto-sync-with-github-action

jobs:
  fetch:
    runs-on: ubuntu-latest
    
    env:
      FORK_REPO_USERNAME: ${{ secrets.FORK_USERNAME }}
      FORK_REPO_TOKEN: ${{ secrets.FORK_GITHUB_TOKEN }}
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Fetch from Fork Repository
      run: |
        git remote add fork_repo https://${{ env.FORK_USERNAME}}:${{ env.FORK_GITHUB_TOKEN}}@github.com/daview-next/daview-ui.git
        git fetch fork_repo

    - name: Merge changes into develop
      run: |
        git checkout -b fork_repo/feature/auto-sync-with-github-action
        git merge origin/feature/auto-sync-with-github-action
        git push origin feature/auto-sync-with-github-action